### ISSUE TITLE
[1.16.5] Screenshot time auto-take takes shot too early

### ISSUE THREAD

**Issue by SteamDoge9000** [AHilyard/AdvancementPlaques#7]
enough said

![aberythe_ore_adv-2022-01-29_14 33 32](https://user-images.githubusercontent.com/38770780/152086721-f4c662ab-84b8-410b-af39-5f3b4c50ef8f.png)

**Comment by AHilyard** [comment]
Not enough said, actually.  I have no idea what this issue means.  Please give me more context about what you are trying to do and what isn't working as expected.

**Comment by EGOIST1372** [comment]
I think what he meant is he has a mod that takes auto screenshot whenever he complete an achievement and since your mod has a shiny start, screenshots that auto screenshot take has that effect on the screenshot he sent since its just shiny and no context in there at start
it would be great to put an option to disable shiny part
thanks in advance

**Comment by AHilyard** [comment]
Ah, thanks for the info.  Most automatic advancement screenshot mods have a built-in delay (for example, Serilum's "Advancement Screenshot" has a 1-second delay).  By configuring Advancement Plaques "FadeInTime" options to the minimum of 0.1, it should work.
For all interested parties: if this does not work, please reopen this issue with more information.
